# Generated by Django 4.2.3 on 2023-07-28 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0002_alter_usuario_cpf_alter_usuario_telefone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cpf',
            field=models.BigIntegerField(),
        ),
    ]
