# Generated by Django 4.2.4 on 2023-08-11 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0008_alter_usuario_cpf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('senha', models.CharField(max_length=50)),
            ],
        ),
    ]
